[package]
name = "starplot"
version = "0.1.0"
authors = ["Aleix Casanovas <aleics.casanovas@gmail.com>"]

[dependencies]
piston = "0.26.0"
piston2d-graphics = "0.18.0"
pistoncore-glutin_window = "0.31.0"
piston2d-opengl_graphics = "0.35.0"
piston_window = "*"
find_folder = "*"
image = "*"